export type MarketCapCompany = {
  rank: number;
  name: string;
  ticker: string;
  marketCap: string;
  marketCapBillion: number;
  country: string;
  region: string;
  sector: string;
  sectorGroup: string;
  driver: string;
  watch: string;
};

export const marketCapSource = {
  name: "CompaniesMarketCap",
  url: "https://companiesmarketcap.com/",
  checkedAt: "2026-08-13",
  totalMarketCap: "$156.211 T",
};

export const marketCapCompanies: MarketCapCompany[] = [
  {
    rank: 1,
    name: "NVIDIA",
    ticker: "NVDA",
    marketCap: "$5.456 T",
    marketCapBillion: 5456.0,
    country: "미국",
    region: "북미",
    sector: "AI 반도체",
    sectorGroup: "AI·반도체",
    driver: "데이터센터 GPU, AI 가속기, CUDA 생태계가 동시에 프리미엄을 만듭니다.",
    watch: "AI 설비투자 속도 둔화와 고객 집중도가 가장 큰 변수입니다.",
  },
  {
    rank: 2,
    name: "Apple",
    ticker: "AAPL",
    marketCap: "$4.455 T",
    marketCapBillion: 4455.0,
    country: "미국",
    region: "북미",
    sector: "소비자 하드웨어",
    sectorGroup: "플랫폼·소프트웨어",
    driver: "아이폰 기반 설치자산, 서비스 매출, 자체 칩 생태계가 방어력을 만듭니다.",
    watch: "중국 수요, 앱스토어 규제, 온디바이스 AI 교체 수요가 관찰 포인트입니다.",
  },
  {
    rank: 3,
    name: "Alphabet",
    ticker: "GOOG",
    marketCap: "$4.206 T",
    marketCapBillion: 4206.0,
    country: "미국",
    region: "북미",
    sector: "검색·클라우드·AI",
    sectorGroup: "플랫폼·소프트웨어",
    driver: "검색 광고 현금흐름과 클라우드, Gemini 기반 AI 제품화가 핵심입니다.",
    watch: "검색 독점 규제와 AI 검색 전환에 따른 광고 단가 변화가 중요합니다.",
  },
  {
    rank: 4,
    name: "Microsoft",
    ticker: "MSFT",
    marketCap: "$3.689 T",
    marketCapBillion: 3689.0,
    country: "미국",
    region: "북미",
    sector: "클라우드·엔터프라이즈",
    sectorGroup: "플랫폼·소프트웨어",
    driver: "Azure, Microsoft 365, Copilot 번들링으로 기업 소프트웨어 지출을 흡수합니다.",
    watch: "AI 인프라 비용과 클라우드 성장률 둔화 여부를 봐야 합니다.",
  },
  {
    rank: 5,
    name: "Amazon",
    ticker: "AMZN",
    marketCap: "$2.859 T",
    marketCapBillion: 2859.0,
    country: "미국",
    region: "북미",
    sector: "전자상거래·클라우드",
    sectorGroup: "플랫폼·소프트웨어",
    driver: "AWS 이익률, 광고 사업, 물류 규모의 경제가 가치 평가를 지탱합니다.",
    watch: "소비 둔화와 클라우드 가격 경쟁이 마진에 미치는 영향이 핵심입니다.",
  },
  {
    rank: 6,
    name: "TSMC",
    ticker: "TSM",
    marketCap: "$2.232 T",
    marketCapBillion: 2232.0,
    country: "대만",
    region: "아시아",
    sector: "파운드리",
    sectorGroup: "AI·반도체",
    driver: "첨단 공정 점유율과 AI 칩 수요가 글로벌 반도체 공급망의 병목 가치를 만듭니다.",
    watch: "지정학 리스크와 설비투자 사이클이 밸류에이션 변동 요인입니다.",
  },
  {
    rank: 7,
    name: "Broadcom",
    ticker: "AVGO",
    marketCap: "$1.987 T",
    marketCapBillion: 1987.0,
    country: "미국",
    region: "북미",
    sector: "반도체·인프라 소프트웨어",
    sectorGroup: "AI·반도체",
    driver: "AI 네트워킹 칩과 VMware 인수 이후 인프라 소프트웨어 현금흐름이 결합됐습니다.",
    watch: "인수 통합, 고객별 ASIC 수요, 부채 축소 속도가 관찰 포인트입니다.",
  },
  {
    rank: 8,
    name: "SpaceX",
    ticker: "SPCX",
    marketCap: "$1.861 T",
    marketCapBillion: 1861.0,
    country: "미국",
    region: "북미",
    sector: "우주·통신 인프라",
    sectorGroup: "산업·인프라",
    driver: "재사용 로켓, Starlink 가입자 기반, 국방·상업 발사 수요가 성장 축입니다.",
    watch: "상장 초기 변동성, 위성망 규제, 대규모 투자 부담을 함께 봐야 합니다.",
  },
  {
    rank: 9,
    name: "Saudi Aramco",
    ticker: "2222.SR",
    marketCap: "$1.706 T",
    marketCapBillion: 1706.0,
    country: "사우디아라비아",
    region: "중동",
    sector: "석유·가스",
    sectorGroup: "에너지·소재",
    driver: "초저원가 원유 생산과 국가 배당 정책이 기업가치의 중심입니다.",
    watch: "유가, 감산 정책, 에너지 전환 속도에 민감합니다.",
  },
  {
    rank: 10,
    name: "Meta Platforms",
    ticker: "META",
    marketCap: "$1.515 T",
    marketCapBillion: 1515.0,
    country: "미국",
    region: "북미",
    sector: "소셜 플랫폼·AI",
    sectorGroup: "플랫폼·소프트웨어",
    driver: "광고 타기팅 회복, Reels, AI 추천 엔진이 수익성을 높입니다.",
    watch: "개인정보 규제와 메타버스 투자 비용의 균형이 중요합니다.",
  },
  {
    rank: 11,
    name: "Tesla",
    ticker: "TSLA",
    marketCap: "$1.342 T",
    marketCapBillion: 1342.0,
    country: "미국",
    region: "북미",
    sector: "전기차·자율주행",
    sectorGroup: "자동차·모빌리티",
    driver: "전기차 규모, 에너지 저장장치, 자율주행 옵션 가치가 복합적으로 반영됩니다.",
    watch: "가격 경쟁, 마진, 자율주행 상용화 속도가 핵심 변수입니다.",
  },
  {
    rank: 12,
    name: "Samsung",
    ticker: "005930.KS",
    marketCap: "$1.240 T",
    marketCapBillion: 1240.0,
    country: "한국",
    region: "아시아",
    sector: "메모리·전자",
    sectorGroup: "AI·반도체",
    driver: "HBM, 메모리 업사이클, 스마트폰·디스플레이 포트폴리오가 복합 가치입니다.",
    watch: "HBM 경쟁력, 메모리 가격 사이클, 원화 환율이 관찰 포인트입니다.",
  },
  {
    rank: 13,
    name: "Berkshire Hathaway",
    ticker: "BRK-B",
    marketCap: "$1.085 T",
    marketCapBillion: 1085.0,
    country: "미국",
    region: "북미",
    sector: "투자 지주",
    sectorGroup: "금융",
    driver: "보험 플로트, 현금 보유, 우량 지분 포트폴리오가 방어형 복리 구조를 만듭니다.",
    watch: "후계 구도와 대형 투자 기회 부재가 할인 요인이 될 수 있습니다.",
  },
  {
    rank: 14,
    name: "Eli Lilly",
    ticker: "LLY",
    marketCap: "$1.077 T",
    marketCapBillion: 1077.0,
    country: "미국",
    region: "북미",
    sector: "비만·당뇨 치료제",
    sectorGroup: "헬스케어",
    driver: "GLP-1 비만 치료제 수요와 파이프라인 확장이 성장 프리미엄을 만듭니다.",
    watch: "생산능력, 약가 압박, 경쟁 신약 출시를 봐야 합니다.",
  },
  {
    rank: 15,
    name: "Micron Technology",
    ticker: "MU",
    marketCap: "$1.072 T",
    marketCapBillion: 1072.0,
    country: "미국",
    region: "북미",
    sector: "메모리 반도체",
    sectorGroup: "AI·반도체",
    driver: "AI 서버용 HBM과 고성능 DRAM 수요가 재평가의 핵심입니다.",
    watch: "메모리 공급 증가와 가격 피크아웃 가능성을 확인해야 합니다.",
  },
  {
    rank: 16,
    name: "JPMorgan Chase",
    ticker: "JPM",
    marketCap: "$965.21 B",
    marketCapBillion: 965.21,
    country: "미국",
    region: "북미",
    sector: "은행",
    sectorGroup: "금융",
    driver: "예금 기반, 투자은행, 리스크 관리 능력이 대형은행 프리미엄을 만듭니다.",
    watch: "금리 하락기 순이자마진과 신용손실 사이클이 변수입니다.",
  },
  {
    rank: 17,
    name: "Walmart",
    ticker: "WMT",
    marketCap: "$920.90 B",
    marketCapBillion: 920.9,
    country: "미국",
    region: "북미",
    sector: "대형 유통",
    sectorGroup: "소비재·유통",
    driver: "저가 유통망, 식료품 트래픽, 멤버십·광고 사업이 안정성을 만듭니다.",
    watch: "임금 비용, 소비 양극화, 온라인 물류 투자 효율을 봐야 합니다.",
  },
  {
    rank: 18,
    name: "SK Hynix",
    ticker: "000660.KS",
    marketCap: "$797.31 B",
    marketCapBillion: 797.31,
    country: "한국",
    region: "아시아",
    sector: "HBM·메모리",
    sectorGroup: "AI·반도체",
    driver: "HBM 공급 우위와 AI 서버 메모리 수요가 기업가치를 끌어올립니다.",
    watch: "고객 집중도와 경쟁사의 HBM 추격 속도가 핵심입니다.",
  },
  {
    rank: 19,
    name: "AMD",
    ticker: "AMD",
    marketCap: "$788.50 B",
    marketCapBillion: 788.5,
    country: "미국",
    region: "북미",
    sector: "AI·CPU·GPU",
    sectorGroup: "AI·반도체",
    driver: "AI 가속기, 서버 CPU, 적응형 반도체 포트폴리오가 성장 옵션입니다.",
    watch: "GPU 생태계 경쟁력과 데이터센터 고객 확보 속도를 봐야 합니다.",
  },
  {
    rank: 20,
    name: "ASML",
    ticker: "ASML",
    marketCap: "$709.77 B",
    marketCapBillion: 709.77,
    country: "네덜란드",
    region: "유럽",
    sector: "반도체 장비",
    sectorGroup: "AI·반도체",
    driver: "EUV 노광장비 독점력과 첨단공정 투자 사이클이 핵심입니다.",
    watch: "대중국 수출 규제와 고객사의 설비투자 지연을 확인해야 합니다.",
  },
  {
    rank: 21,
    name: "Visa",
    ticker: "V",
    marketCap: "$682.31 B",
    marketCapBillion: 682.31,
    country: "미국",
    region: "북미",
    sector: "결제 네트워크",
    sectorGroup: "금융",
    driver: "글로벌 카드 네트워크와 높은 영업 레버리지가 강점입니다.",
    watch: "수수료 규제와 실시간 계좌이체 네트워크의 대체 가능성을 봐야 합니다.",
  },
  {
    rank: 22,
    name: "Exxon Mobil",
    ticker: "XOM",
    marketCap: "$652.19 B",
    marketCapBillion: 652.19,
    country: "미국",
    region: "북미",
    sector: "석유·가스",
    sectorGroup: "에너지·소재",
    driver: "상류 생산, 정유, 화학까지 이어지는 통합 에너지 포트폴리오가 강점입니다.",
    watch: "유가와 정제마진, 탄소 규제 비용이 가치 변동 요인입니다.",
  },
  {
    rank: 23,
    name: "Johnson & Johnson",
    ticker: "JNJ",
    marketCap: "$631.58 B",
    marketCapBillion: 631.58,
    country: "미국",
    region: "북미",
    sector: "의약품·의료기기",
    sectorGroup: "헬스케어",
    driver: "의약품과 의료기기 포트폴리오가 경기 방어형 현금흐름을 만듭니다.",
    watch: "특허 만료와 소송 비용, 신약 생산성이 관찰 포인트입니다.",
  },
  {
    rank: 24,
    name: "CXMT",
    ticker: "688825.SS",
    marketCap: "$555.40 B",
    marketCapBillion: 555.4,
    country: "중국",
    region: "아시아",
    sector: "메모리 반도체",
    sectorGroup: "AI·반도체",
    driver: "중국 최대 D램·낸드 메모리 제조사(창신메모리)로, 미국 제재 속 자국 반도체 자급률 확대의 핵심 수혜주입니다. 상장 직후 시가총액이 급등하며 글로벌 100대 기업에 진입했습니다.",
    watch: "미·중 반도체 제재 강도, HBM 기술 추격 속도, 수율 개선 여부와 중국 내 수요 기반을 봐야 합니다.",
  },
  {
    rank: 25,
    name: "Intel",
    ticker: "INTC",
    marketCap: "$549.41 B",
    marketCapBillion: 549.41,
    country: "미국",
    region: "북미",
    sector: "반도체·파운드리",
    sectorGroup: "AI·반도체",
    driver: "공정 회복, 파운드리 전략, PC·서버 CPU 기반이 재평가 포인트입니다.",
    watch: "막대한 설비투자와 공정 로드맵 실행력이 리스크입니다.",
  },
  {
    rank: 26,
    name: "Tencent",
    ticker: "TCEHY",
    marketCap: "$497.52 B",
    marketCapBillion: 497.52,
    country: "중국",
    region: "아시아",
    sector: "게임·소셜 플랫폼",
    sectorGroup: "플랫폼·소프트웨어",
    driver: "WeChat 생태계, 게임, 핀테크 지분 가치가 복합 성장축입니다.",
    watch: "중국 플랫폼 규제와 게임 승인 사이클을 확인해야 합니다.",
  },
  {
    rank: 27,
    name: "Mastercard",
    ticker: "MA",
    marketCap: "$496.73 B",
    marketCapBillion: 496.73,
    country: "미국",
    region: "북미",
    sector: "결제 네트워크",
    sectorGroup: "금융",
    driver: "글로벌 결제 네트워크, 데이터 서비스, 국경간 결제가 이익률을 높입니다.",
    watch: "카드 수수료 규제와 핀테크 대체 경쟁을 관찰해야 합니다.",
  },
  {
    rank: 28,
    name: "Oracle",
    ticker: "ORCL",
    marketCap: "$449.98 B",
    marketCapBillion: 449.98,
    country: "미국",
    region: "북미",
    sector: "엔터프라이즈 소프트웨어",
    sectorGroup: "플랫폼·소프트웨어",
    driver: "데이터베이스 락인과 클라우드 인프라 수요가 재평가를 이끕니다.",
    watch: "클라우드 투자 부담과 경쟁사 대비 성장률을 봐야 합니다.",
  },
  {
    rank: 29,
    name: "Bank of America",
    ticker: "BAC",
    marketCap: "$448.16 B",
    marketCapBillion: 448.16,
    country: "미국",
    region: "북미",
    sector: "은행",
    sectorGroup: "금융",
    driver: "소매 예금 기반과 자산관리, 기업금융이 수익 포트폴리오를 만듭니다.",
    watch: "금리 민감도와 상업용 부동산 신용위험을 봐야 합니다.",
  },
  {
    rank: 30,
    name: "Cisco",
    ticker: "CSCO",
    marketCap: "$447.23 B",
    marketCapBillion: 447.23,
    country: "미국",
    region: "북미",
    sector: "네트워크 장비",
    sectorGroup: "플랫폼·소프트웨어",
    driver: "기업 네트워크, 보안, 관측성 소프트웨어 전환이 안정 매출을 만듭니다.",
    watch: "하드웨어 교체 사이클과 소프트웨어 전환 속도가 관찰 포인트입니다.",
  },
  {
    rank: 31,
    name: "AbbVie",
    ticker: "ABBV",
    marketCap: "$443.22 B",
    marketCapBillion: 443.22,
    country: "미국",
    region: "북미",
    sector: "제약",
    sectorGroup: "헬스케어",
    driver: "면역학·항암제 포트폴리오와 인수 기반 파이프라인이 성장축입니다.",
    watch: "주력 약품 특허절벽 이후 매출 회복력이 중요합니다.",
  },
  {
    rank: 32,
    name: "Palantir",
    ticker: "PLTR",
    marketCap: "$430.17 B",
    marketCapBillion: 430.17,
    country: "미국",
    region: "북미",
    sector: "AI 데이터 플랫폼",
    sectorGroup: "플랫폼·소프트웨어",
    driver: "정부·기업 데이터 운영 플랫폼과 AI 워크플로 도입이 성장축입니다.",
    watch: "높은 밸류에이션과 계약 집중도를 함께 확인해야 합니다.",
  },
  {
    rank: 33,
    name: "Costco",
    ticker: "COST",
    marketCap: "$426.56 B",
    marketCapBillion: 426.56,
    country: "미국",
    region: "북미",
    sector: "회원제 유통",
    sectorGroup: "소비재·유통",
    driver: "멤버십 갱신률, 낮은 가격 신뢰, 재고 회전이 프리미엄의 기반입니다.",
    watch: "밸류에이션 부담과 멤버십 가격 인상 속도를 봐야 합니다.",
  },
  {
    rank: 34,
    name: "Applied Materials",
    ticker: "AMAT",
    marketCap: "$424.40 B",
    marketCapBillion: 424.4,
    country: "미국",
    region: "북미",
    sector: "반도체 장비",
    sectorGroup: "AI·반도체",
    driver: "웨이퍼 제조 장비 전반의 폭넓은 포트폴리오가 강점입니다.",
    watch: "고객 설비투자와 장비 수출 규제 변화를 봐야 합니다.",
  },
  {
    rank: 35,
    name: "Lam Research",
    ticker: "LRCX",
    marketCap: "$421.70 B",
    marketCapBillion: 421.7,
    country: "미국",
    region: "북미",
    sector: "반도체 장비",
    sectorGroup: "AI·반도체",
    driver: "식각·증착 장비 수요와 메모리 투자 회복이 핵심입니다.",
    watch: "장비 발주 사이클과 중국 수출 제한이 변수입니다.",
  },
  {
    rank: 36,
    name: "China Construction Bank",
    ticker: "601939.SS",
    marketCap: "$399.63 B",
    marketCapBillion: 399.63,
    country: "중국",
    region: "아시아",
    sector: "은행",
    sectorGroup: "금융",
    driver: "대형 국유은행 기반의 예금 규모와 기업금융 네트워크가 강점입니다.",
    watch: "중국 부동산 신용위험과 순이자마진 압박을 봐야 합니다.",
  },
  {
    rank: 37,
    name: "Caterpillar",
    ticker: "CAT",
    marketCap: "$392.83 B",
    marketCapBillion: 392.83,
    country: "미국",
    region: "북미",
    sector: "건설·광산 장비",
    sectorGroup: "산업·인프라",
    driver: "인프라 투자, 광산 장비, 서비스 부품 매출이 사이클을 완충합니다.",
    watch: "원자재 경기와 건설 투자 둔화가 리스크입니다.",
  },
  {
    rank: 38,
    name: "Chevron",
    ticker: "CVX",
    marketCap: "$387.80 B",
    marketCapBillion: 387.8,
    country: "미국",
    region: "북미",
    sector: "석유·가스",
    sectorGroup: "에너지·소재",
    driver: "저비용 생산자산과 배당·자사주 환원 정책이 투자 매력입니다.",
    watch: "유가 하락과 대형 인수 통합 리스크를 봐야 합니다.",
  },
  {
    rank: 39,
    name: "Coca-Cola",
    ticker: "KO",
    marketCap: "$376.12 B",
    marketCapBillion: 376.12,
    country: "미국",
    region: "북미",
    sector: "음료",
    sectorGroup: "소비재·유통",
    driver: "글로벌 브랜드, 병입 파트너망, 가격 결정력이 안정 현금흐름을 만듭니다.",
    watch: "원가 상승과 건강 규제, 신흥국 환율을 봐야 합니다.",
  },
  {
    rank: 40,
    name: "General Electric",
    ticker: "GE",
    marketCap: "$374.18 B",
    marketCapBillion: 374.18,
    country: "미국",
    region: "북미",
    sector: "항공 엔진",
    sectorGroup: "산업·인프라",
    driver: "항공 엔진 서비스 매출과 상업 항공 수요 회복이 핵심입니다.",
    watch: "공급망 병목과 항공기 인도 지연을 봐야 합니다.",
  },
  {
    rank: 41,
    name: "Roche",
    ticker: "RO.SW",
    marketCap: "$360.00 B",
    marketCapBillion: 360.0,
    country: "스위스",
    region: "유럽",
    sector: "제약·진단",
    sectorGroup: "헬스케어",
    driver: "항암제, 진단 사업, 신약 파이프라인이 장기 가치를 만듭니다.",
    watch: "특허 만료와 후기 임상 실패 가능성이 리스크입니다.",
  },
  {
    rank: 42,
    name: "UnitedHealth",
    ticker: "UNH",
    marketCap: "$358.19 B",
    marketCapBillion: 358.19,
    country: "미국",
    region: "북미",
    sector: "건강보험·헬스케어",
    sectorGroup: "헬스케어",
    driver: "보험, 약국급여관리, 의료서비스 수직 통합이 방어력을 만듭니다.",
    watch: "의료비율 상승과 규제 조사가 주요 변수입니다.",
  },
  {
    rank: 43,
    name: "HSBC",
    ticker: "HSBC",
    marketCap: "$357.58 B",
    marketCapBillion: 357.58,
    country: "영국",
    region: "유럽",
    sector: "글로벌 은행",
    sectorGroup: "금융",
    driver: "아시아 중심 예금 기반과 무역금융 네트워크가 차별점입니다.",
    watch: "홍콩·중국 경기, 금리 하락, 규제 비용을 봐야 합니다.",
  },
  {
    rank: 44,
    name: "Morgan Stanley",
    ticker: "MS",
    marketCap: "$343.29 B",
    marketCapBillion: 343.29,
    country: "미국",
    region: "북미",
    sector: "투자은행·자산관리",
    sectorGroup: "금융",
    driver: "자산관리 수수료와 투자은행 회복이 수익 안정성을 높입니다.",
    watch: "자본시장 침체와 신용 리스크 확대를 봐야 합니다.",
  },
  {
    rank: 45,
    name: "Home Depot",
    ticker: "HD",
    marketCap: "$340.71 B",
    marketCapBillion: 340.71,
    country: "미국",
    region: "북미",
    sector: "주택개선 유통",
    sectorGroup: "소비재·유통",
    driver: "전문 시공 고객, 매장망, 주택 보수 수요가 안정 매출을 만듭니다.",
    watch: "주택 거래 둔화와 금리 민감 소비가 변수입니다.",
  },
  {
    rank: 46,
    name: "Agricultural Bank of China",
    ticker: "601288.SS",
    marketCap: "$340.52 B",
    marketCapBillion: 340.52,
    country: "중국",
    region: "아시아",
    sector: "은행",
    sectorGroup: "금융",
    driver: "국유은행의 예금 기반과 농촌·기업금융 네트워크가 핵심입니다.",
    watch: "정책금융 부담과 신용비용 변화를 관찰해야 합니다.",
  },
  {
    rank: 47,
    name: "Procter & Gamble",
    ticker: "PG",
    marketCap: "$335.92 B",
    marketCapBillion: 335.92,
    country: "미국",
    region: "북미",
    sector: "생활소비재",
    sectorGroup: "소비재·유통",
    driver: "필수소비재 브랜드와 가격 전가력이 경기 방어형 가치를 만듭니다.",
    watch: "원가, 환율, 소비자 다운트레이딩을 확인해야 합니다.",
  },
  {
    rank: 48,
    name: "Merck",
    ticker: "MRK",
    marketCap: "$334.42 B",
    marketCapBillion: 334.42,
    country: "미국",
    region: "북미",
    sector: "제약",
    sectorGroup: "헬스케어",
    driver: "면역항암제와 백신 포트폴리오가 현금흐름의 중심입니다.",
    watch: "Keytruda 특허 만료와 후속 파이프라인 성공이 중요합니다.",
  },
  {
    rank: 49,
    name: "ICBC",
    ticker: "1398.HK",
    marketCap: "$327.48 B",
    marketCapBillion: 327.48,
    country: "중국",
    region: "아시아",
    sector: "은행",
    sectorGroup: "금융",
    driver: "세계 최대급 예금·대출 규모와 국유 금융 인프라가 강점입니다.",
    watch: "중국 경기와 부동산 신용위험이 밸류에이션을 좌우합니다.",
  },
  {
    rank: 50,
    name: "Netflix",
    ticker: "NFLX",
    marketCap: "$325.78 B",
    marketCapBillion: 325.78,
    country: "미국",
    region: "북미",
    sector: "스트리밍·콘텐츠",
    sectorGroup: "플랫폼·소프트웨어",
    driver: "글로벌 가입자 기반, 광고 요금제, 콘텐츠 추천 알고리즘이 성장축입니다.",
    watch: "콘텐츠 비용과 지역별 가입자 성장 둔화를 봐야 합니다.",
  },
  {
    rank: 51,
    name: "Palo Alto Networks",
    ticker: "PANW",
    marketCap: "$322.73 B",
    marketCapBillion: 322.73,
    country: "미국",
    region: "북미",
    sector: "사이버 보안",
    sectorGroup: "플랫폼·소프트웨어",
    driver: "클라우드·AI 보안 플랫폼 선도 기업으로, Strata/XSIAM 등 구독형 보안 서비스가 성장을 이끌고 있습니다. AI 보안 수요 확대의 대표 수혜주입니다.",
    watch: "보안 업계 가격 경쟁 심화, 크라우드스트라이크 등 경쟁사 대비 성장률과 플랫폼 전환 속도를 봐야 합니다.",
  },
  {
    rank: 52,
    name: "Dell",
    ticker: "DELL",
    marketCap: "$319.52 B",
    marketCapBillion: 319.52,
    country: "미국",
    region: "북미",
    sector: "서버·PC 인프라",
    sectorGroup: "플랫폼·소프트웨어",
    driver: "AI 서버 수요와 기업 인프라 교체 사이클이 재평가를 이끕니다.",
    watch: "PC 수요 둔화와 서버 마진 압박을 봐야 합니다.",
  },
  {
    rank: 53,
    name: "Goldman Sachs",
    ticker: "GS",
    marketCap: "$303.58 B",
    marketCapBillion: 303.58,
    country: "미국",
    region: "북미",
    sector: "투자은행",
    sectorGroup: "금융",
    driver: "M&A, 트레이딩, 자산운용 회복 시 레버리지가 큽니다.",
    watch: "자본시장 사이클과 규제 자본 요구가 핵심 변수입니다.",
  },
  {
    rank: 54,
    name: "Royal Bank of Canada",
    ticker: "RY",
    marketCap: "$298.77 B",
    marketCapBillion: 298.77,
    country: "캐나다",
    region: "북미",
    sector: "은행",
    sectorGroup: "금융",
    driver: "캐나다 소매금융, 자산관리, 자본시장 사업이 안정성을 만듭니다.",
    watch: "주택대출 건전성과 금리 하락기 마진 변화를 봐야 합니다.",
  },
  {
    rank: 55,
    name: "Arm Holdings",
    ticker: "ARM",
    marketCap: "$297.59 B",
    marketCapBillion: 297.59,
    country: "영국",
    region: "유럽",
    sector: "반도체 IP",
    sectorGroup: "AI·반도체",
    driver: "저전력 CPU 설계 IP와 모바일·서버 확장 로열티가 핵심입니다.",
    watch: "고객 내재화와 로열티 인상 수용력이 관찰 포인트입니다.",
  },
  {
    rank: 56,
    name: "RTX",
    ticker: "RTX",
    marketCap: "$297.15 B",
    marketCapBillion: 297.15,
    country: "미국",
    region: "북미",
    sector: "항공우주·방산",
    sectorGroup: "산업·인프라",
    driver: "방산 수주, 항공부품, 엔진 서비스 매출이 장기 수요를 만듭니다.",
    watch: "엔진 품질 비용과 국방예산 사이클을 봐야 합니다.",
  },
  {
    rank: 57,
    name: "Philip Morris International",
    ticker: "PM",
    marketCap: "$294.43 B",
    marketCapBillion: 294.43,
    country: "미국",
    region: "북미",
    sector: "담배·무연제품",
    sectorGroup: "소비재·유통",
    driver: "아이코스 등 무연 제품 전환과 강한 가격 결정력이 핵심입니다.",
    watch: "니코틴 규제와 신제품 과세 정책을 봐야 합니다.",
  },
  {
    rank: 58,
    name: "Alibaba",
    ticker: "BABA",
    marketCap: "$292.80 B",
    marketCapBillion: 292.8,
    country: "중국",
    region: "아시아",
    sector: "전자상거래·클라우드",
    sectorGroup: "플랫폼·소프트웨어",
    driver: "중국 커머스, 클라우드, 해외 전자상거래 확장이 가치축입니다.",
    watch: "중국 소비 회복과 플랫폼 규제, 경쟁 심화를 봐야 합니다.",
  },
  {
    rank: 59,
    name: "Novartis",
    ticker: "NVS",
    marketCap: "$288.37 B",
    marketCapBillion: 288.37,
    country: "스위스",
    region: "유럽",
    sector: "제약",
    sectorGroup: "헬스케어",
    driver: "심혈관·면역·항암 파이프라인 집중 전략이 성장성을 만듭니다.",
    watch: "특허 만료와 약가 규제 압력이 관찰 포인트입니다.",
  },
  {
    rank: 60,
    name: "Bank of China",
    ticker: "601988.SS",
    marketCap: "$284.34 B",
    marketCapBillion: 284.34,
    country: "중국",
    region: "아시아",
    sector: "은행",
    sectorGroup: "금융",
    driver: "국제 결제, 기업금융, 국유은행 예금 기반이 핵심입니다.",
    watch: "중국 신용 사이클과 정책성 대출 부담을 봐야 합니다.",
  },
  {
    rank: 61,
    name: "GE Vernova",
    ticker: "GEV",
    marketCap: "$279.49 B",
    marketCapBillion: 279.49,
    country: "미국",
    region: "북미",
    sector: "전력·에너지 장비",
    sectorGroup: "산업·인프라",
    driver: "전력망 투자, 가스터빈, 재생에너지 장비 수요가 성장축입니다.",
    watch: "프로젝트 마진과 공급망 실행력이 핵심입니다.",
  },
  {
    rank: 62,
    name: "KLA",
    ticker: "KLAC",
    marketCap: "$273.55 B",
    marketCapBillion: 273.55,
    country: "미국",
    region: "북미",
    sector: "반도체 검사장비",
    sectorGroup: "AI·반도체",
    driver: "공정 미세화에 필요한 검사·계측 장비 수요가 구조적으로 증가합니다.",
    watch: "반도체 설비투자 사이클과 규제 리스크를 봐야 합니다.",
  },
  {
    rank: 63,
    name: "CATL",
    ticker: "300750.SZ",
    marketCap: "$271.94 B",
    marketCapBillion: 271.94,
    country: "중국",
    region: "아시아",
    sector: "배터리",
    sectorGroup: "자동차·모빌리티",
    driver: "전기차 배터리 점유율과 에너지저장장치 수요가 핵심입니다.",
    watch: "배터리 가격 하락, 원재료, 완성차 업체 내재화를 봐야 합니다.",
  },
  {
    rank: 64,
    name: "Wells Fargo",
    ticker: "WFC",
    marketCap: "$266.44 B",
    marketCapBillion: 266.44,
    country: "미국",
    region: "북미",
    sector: "은행",
    sectorGroup: "금융",
    driver: "미국 소매금융과 비용 구조 개선이 재평가 요인입니다.",
    watch: "규제 제재 해소와 신용비용 증가 여부가 중요합니다.",
  },
  {
    rank: 65,
    name: "LVMH",
    ticker: "MC.PA",
    marketCap: "$261.55 B",
    marketCapBillion: 261.55,
    country: "프랑스",
    region: "유럽",
    sector: "럭셔리",
    sectorGroup: "소비재·유통",
    driver: "루이비통·디올 등 브랜드 포트폴리오와 가격 결정력이 핵심입니다.",
    watch: "중국 명품 소비와 환율, 재고 조정이 변수입니다.",
  },
  {
    rank: 66,
    name: "Mitsubishi UFJ Financial",
    ticker: "MUFG",
    marketCap: "$260.49 B",
    marketCapBillion: 260.49,
    country: "일본",
    region: "아시아",
    sector: "은행",
    sectorGroup: "금융",
    driver: "일본 금리 정상화와 대형 금융그룹의 예대마진 회복이 핵심입니다.",
    watch: "금리 정책 변화와 해외 신용위험을 봐야 합니다.",
  },
  {
    rank: 67,
    name: "Arista Networks",
    ticker: "ANET",
    marketCap: "$256.81 B",
    marketCapBillion: 256.81,
    country: "미국",
    region: "북미",
    sector: "데이터센터 네트워크",
    sectorGroup: "AI·반도체",
    driver: "AI 클러스터용 고속 스위칭과 클라우드 고객 수요가 핵심입니다.",
    watch: "대형 고객 발주 변동성과 네트워크 장비 경쟁을 봐야 합니다.",
  },
  {
    rank: 68,
    name: "Nestle",
    ticker: "NESN.SW",
    marketCap: "$256.17 B",
    marketCapBillion: 256.17,
    country: "스위스",
    region: "유럽",
    sector: "식품·음료",
    sectorGroup: "소비재·유통",
    driver: "글로벌 식품 브랜드와 가격 전가력이 안정 현금흐름을 만듭니다.",
    watch: "원재료 비용과 건강·영양 트렌드 변화가 관찰 포인트입니다.",
  },
  {
    rank: 69,
    name: "Kweichow Moutai",
    ticker: "600519.SS",
    marketCap: "$251.28 B",
    marketCapBillion: 251.28,
    country: "중국",
    region: "아시아",
    sector: "프리미엄 주류",
    sectorGroup: "소비재·유통",
    driver: "희소한 브랜드, 고마진 백주, 유통 통제력이 핵심입니다.",
    watch: "중국 고가 소비와 정부 접대 규제 변화를 봐야 합니다.",
  },
  {
    rank: 70,
    name: "Siemens",
    ticker: "SIE.DE",
    marketCap: "$249.93 B",
    marketCapBillion: 249.93,
    country: "독일",
    region: "유럽",
    sector: "산업 자동화",
    sectorGroup: "산업·인프라",
    driver: "공장 자동화, 전력 인프라, 산업 소프트웨어가 성장축입니다.",
    watch: "제조업 경기와 중국 자동화 투자 둔화를 확인해야 합니다.",
  },
  {
    rank: 71,
    name: "Texas Instruments",
    ticker: "TXN",
    marketCap: "$249.70 B",
    marketCapBillion: 249.7,
    country: "미국",
    region: "북미",
    sector: "아날로그 반도체",
    sectorGroup: "AI·반도체",
    driver: "산업·자동차용 아날로그 칩과 긴 제품 수명이 강점입니다.",
    watch: "산업 경기 둔화와 재고 조정 사이클을 봐야 합니다.",
  },
  {
    rank: 72,
    name: "Shell",
    ticker: "SHEL",
    marketCap: "$248.36 B",
    marketCapBillion: 248.36,
    country: "영국",
    region: "유럽",
    sector: "석유·가스",
    sectorGroup: "에너지·소재",
    driver: "LNG, 상류 생산, 주주환원이 에너지 대형주의 핵심 가치입니다.",
    watch: "유가, LNG 가격, 에너지 전환 투자 수익성을 봐야 합니다.",
  },
  {
    rank: 73,
    name: "AstraZeneca",
    ticker: "AZN",
    marketCap: "$243.86 B",
    marketCapBillion: 243.86,
    country: "영국",
    region: "유럽",
    sector: "제약",
    sectorGroup: "헬스케어",
    driver: "항암·희귀질환·호흡기 파이프라인이 글로벌 성장축입니다.",
    watch: "임상 결과와 중국 매출 성장 지속성을 확인해야 합니다.",
  },
  {
    rank: 74,
    name: "SAP",
    ticker: "SAP",
    marketCap: "$241.55 B",
    marketCapBillion: 241.55,
    country: "독일",
    region: "유럽",
    sector: "기업용 소프트웨어",
    sectorGroup: "플랫폼·소프트웨어",
    driver: "ERP·클라우드 전환, 비즈니스 AI 통합이 기업 소프트웨어 리더십을 만듭니다.",
    watch: "클라우드 전환 속도와 경쟁사 점유율 변화를 봐야 합니다.",
  },
  {
    rank: 75,
    name: "L'Oreal",
    ticker: "OR.PA",
    marketCap: "$235.37 B",
    marketCapBillion: 235.37,
    country: "프랑스",
    region: "유럽",
    sector: "화장품",
    sectorGroup: "소비재·유통",
    driver: "글로벌 뷰티 브랜드, 프리미엄 라인, 지역 다변화가 강점입니다.",
    watch: "중국 소비 둔화와 마케팅 비용 증가를 봐야 합니다.",
  },
  {
    rank: 76,
    name: "Citigroup",
    ticker: "C",
    marketCap: "$232.71 B",
    marketCapBillion: 232.71,
    country: "미국",
    region: "북미",
    sector: "글로벌 은행",
    sectorGroup: "금융",
    driver: "글로벌 결제·무역금융 네트워크와 구조조정 효과가 재평가 요인입니다.",
    watch: "비핵심 자산 정리와 규제 자본 부담을 봐야 합니다.",
  },
  {
    rank: 77,
    name: "American Express",
    ticker: "AXP",
    marketCap: "$232.07 B",
    marketCapBillion: 232.07,
    country: "미국",
    region: "북미",
    sector: "프리미엄 결제",
    sectorGroup: "금융",
    driver: "고소득 고객 기반, 카드 수수료, 여행·소비 회복이 강점입니다.",
    watch: "신용손실과 프리미엄 소비 둔화를 봐야 합니다.",
  },
  {
    rank: 78,
    name: "CrowdStrike",
    ticker: "CRWD",
    marketCap: "$229.64 B",
    marketCapBillion: 229.64,
    country: "미국",
    region: "북미",
    sector: "사이버 보안",
    sectorGroup: "플랫폼·소프트웨어",
    driver: "클라우드 보안, EDR, Falcon 플랫폼의 구독형 모델이 높은 성장과 마진을 만듭니다.",
    watch: "경쟁 심화와 기업 IT 예산 변동, 보안 사고 이후 신뢰 회복이 중요합니다.",
  },
  {
    rank: 79,
    name: "Amgen",
    ticker: "AMGN",
    marketCap: "$225.51 B",
    marketCapBillion: 225.51,
    country: "미국",
    region: "북미",
    sector: "바이오제약",
    sectorGroup: "헬스케어",
    driver: "노화·염증·종양학 분야 바이오의약품 포트폴리오와 Repatha·Prolia 등 블록버스터가 강점입니다.",
    watch: "바이오시밀러 경쟁과 신약 파이프라인 성과, 특허 만료 영향을 봐야 합니다.",
  },
  {
    rank: 80,
    name: "International Holding Company",
    ticker: "IHC.AE",
    marketCap: "$224.45 B",
    marketCapBillion: 224.45,
    country: "UAE",
    region: "중동",
    sector: "복합 지주",
    sectorGroup: "산업·인프라",
    driver: "UAE 기반 투자 포트폴리오와 지주 구조가 기업가치를 구성합니다.",
    watch: "거버넌스, 유동성, 포트폴리오 평가 투명성을 확인해야 합니다.",
  },
  {
    rank: 81,
    name: "China Mobile",
    ticker: "0941.HK",
    marketCap: "$223.98 B",
    marketCapBillion: 223.98,
    country: "중국",
    region: "아시아",
    sector: "통신",
    sectorGroup: "통신·미디어",
    driver: "중국 최대 통신 가입자 기반과 5G·클라우드 인프라가 현금흐름을 만듭니다.",
    watch: "요금 규제와 설비투자 부담을 봐야 합니다.",
  },
  {
    rank: 82,
    name: "Toyota",
    ticker: "TM",
    marketCap: "$223.45 B",
    marketCapBillion: 223.45,
    country: "일본",
    region: "아시아",
    sector: "자동차",
    sectorGroup: "자동차·모빌리티",
    driver: "하이브리드 경쟁력, 글로벌 생산망, 품질 신뢰가 핵심입니다.",
    watch: "전기차 전환 속도와 환율, 중국 경쟁을 봐야 합니다.",
  },
  {
    rank: 83,
    name: "IBM",
    ticker: "IBM",
    marketCap: "$223.41 B",
    marketCapBillion: 223.41,
    country: "미국",
    region: "북미",
    sector: "하이브리드 클라우드·AI",
    sectorGroup: "플랫폼·소프트웨어",
    driver: "Red Hat, 메인프레임, 기업 AI 컨설팅이 안정 매출을 만듭니다.",
    watch: "레거시 매출 감소와 AI 서비스 성장률을 봐야 합니다.",
  },
  {
    rank: 84,
    name: "Sandisk",
    ticker: "SNDK",
    marketCap: "$223.10 B",
    marketCapBillion: 223.1,
    country: "미국",
    region: "북미",
    sector: "메모리 반도체",
    sectorGroup: "AI·반도체",
    driver: "낸드플래시 분사 후 AI 스토리지 수요로 실적 회복이 가속화되고 있습니다.",
    watch: "기업용 SSD(eSSD) 가격·낸드 공급과 AI 서버 스토리지 투자 흐름을 봐야 합니다.",
  },
  {
    rank: 85,
    name: "BHP Group",
    ticker: "BHP",
    marketCap: "$221.59 B",
    marketCapBillion: 221.59,
    country: "호주",
    region: "오세아니아",
    sector: "광산·철광석",
    sectorGroup: "에너지·소재",
    driver: "철광석, 구리, 원자재 포트폴리오가 글로벌 산업 수요와 연결됩니다.",
    watch: "중국 건설 경기와 원자재 가격 변동성이 핵심입니다.",
  },
  {
    rank: 86,
    name: "Linde",
    ticker: "LIN",
    marketCap: "$220.44 B",
    marketCapBillion: 220.44,
    country: "영국",
    region: "유럽",
    sector: "산업가스",
    sectorGroup: "에너지·소재",
    driver: "장기 공급계약과 산업가스 필수성이 높은 마진을 만듭니다.",
    watch: "산업 생산 둔화와 에너지 비용이 변수입니다.",
  },
  {
    rank: 87,
    name: "Thermo Fisher Scientific",
    ticker: "TMO",
    marketCap: "$220.32 B",
    marketCapBillion: 220.32,
    country: "미국",
    region: "북미",
    sector: "생명과학 장비",
    sectorGroup: "헬스케어",
    driver: "분석 장비, 시약, 임험 서비스를 아우르는 생명과학 토탈 솔루션이 강점입니다.",
    watch: "R&D 예산 변동, 중국 시장 리스크, 인수 통합 효율을 봐야 합니다.",
  },
  {
    rank: 88,
    name: "PetroChina",
    ticker: "0857.HK",
    marketCap: "$219.25 B",
    marketCapBillion: 219.25,
    country: "중국",
    region: "아시아",
    sector: "석유·가스",
    sectorGroup: "에너지·소재",
    driver: "중국 내 에너지 공급망과 상류·하류 통합 구조가 핵심입니다.",
    watch: "유가와 중국 에너지 정책, 정제마진을 봐야 합니다.",
  },
  {
    rank: 89,
    name: "Santander",
    ticker: "SAN",
    marketCap: "$210.86 B",
    marketCapBillion: 210.86,
    country: "스페인",
    region: "유럽",
    sector: "은행",
    sectorGroup: "금융",
    driver: "유럽·라틴아메리카 소매금융 네트워크와 디지털 전환이 성장축입니다.",
    watch: "신흥국 환율 리스크와 유럽 금리 사이클을 봐야 합니다.",
  },
  {
    rank: 90,
    name: "MediaTek",
    ticker: "2454.TW",
    marketCap: "$209.94 B",
    marketCapBillion: 209.94,
    country: "대만",
    region: "아시아",
    sector: "반도체 설계",
    sectorGroup: "AI·반도체",
    driver: "스마트폰 AP·AI 칩 설계 1위권, 엣지 AI로 확장",
    watch: "AI 폰·온디바이스 AI 수요로 모바일 SoC 매출 성장 기대",
  },
  {
    rank: 91,
    name: "Seagate Technology",
    ticker: "STX",
    marketCap: "$209.15 B",
    marketCapBillion: 209.15,
    country: "아일랜드",
    region: "북미",
    sector: "저장장치",
    sectorGroup: "AI·반도체",
    driver: "AI 데이터센터·클라우드 투자 확대로 대용량 HDD 수요가 급증하고 있습니다.",
    watch: "엔터프라이즈 SSD와 신제품(30TB+ HAMR) 출시, 클라우드 자본지출 사이클을 봐야 합니다.",
  },
  {
    rank: 92,
    name: "Inditex",
    ticker: "ITX.MC",
    marketCap: "$207.84 B",
    marketCapBillion: 207.84,
    country: "스페인",
    region: "유럽",
    sector: "패션 리테일",
    sectorGroup: "소비재·유통",
    driver: "Zara 중심의 빠른 재고 회전과 글로벌 매장망이 강점입니다.",
    watch: "소비 둔화, 재고 리스크, 온라인 경쟁을 봐야 합니다.",
  },
  {
    rank: 93,
    name: "Novo Nordisk",
    ticker: "NVO",
    marketCap: "$204.68 B",
    marketCapBillion: 204.68,
    country: "덴마크",
    region: "유럽",
    sector: "비만·당뇨 치료제",
    sectorGroup: "헬스케어",
    driver: "GLP-1 치료제 리더십과 글로벌 당뇨·비만 수요가 핵심입니다.",
    watch: "경쟁 약물, 공급 병목, 약가 압박을 확인해야 합니다.",
  },
  {
    rank: 94,
    name: "Amphenol",
    ticker: "APH",
    marketCap: "$204.36 B",
    marketCapBillion: 204.36,
    country: "미국",
    region: "북미",
    sector: "데이터센터 커넥터",
    sectorGroup: "AI·반도체",
    driver: "AI 데이터센터용 커넥터·케이블 최대 제조사로, 엔비디아 등 AI 인프라 투자 확대의 직접 수혜주입니다. 글로벌 전자부품 점유율 1위입니다.",
    watch: "AI 인프라 투자 사이클 둔화 시 실적 민감도, M&A 통합 부담과 부채 수준을 봐야 합니다.",
  },
  {
    rank: 95,
    name: "Shopify",
    ticker: "SHOP",
    marketCap: "$203.97 B",
    marketCapBillion: 203.97,
    country: "캐나다",
    region: "북미",
    sector: "전자상거래·클라우드",
    sectorGroup: "플랫폼·소프트웨어",
    driver: "북미 전자상거래 플랫폼 1위로, AI 기반 상거래 도구와 오프라인 매장 통합 확장이 매출 성장을 이끕니다.",
    watch: "GMV 성장률 둔화와 소비 경기, 기업용(B2B) 판매 확대 성과를 봐야 합니다.",
  },
  {
    rank: 96,
    name: "Toronto Dominion Bank",
    ticker: "TD",
    marketCap: "$203.38 B",
    marketCapBillion: 203.38,
    country: "캐나다",
    region: "북미",
    sector: "은행",
    sectorGroup: "금융",
    driver: "캐나다 2위 은행으로 소매예금 기반과 북미 금융 네트워크가 안정성을 만듭니다.",
    watch: "금리 민감도와 캐나다 주택시장 위험, 미국 소매 확장 성과를 봐야 합니다.",
  },
  {
    rank: 97,
    name: "Schneider Electric",
    ticker: "SU.PA",
    marketCap: "$200.51 B",
    marketCapBillion: 200.51,
    country: "프랑스",
    region: "유럽",
    sector: "전력·에너지 장비",
    sectorGroup: "산업·인프라",
    driver: "전력망·배전 자동화 글로벌 1위로, AI 데이터센터와 재생에너지 확대에 따른 전력 인프라 투자 수혜를 받습니다.",
    watch: "전력 설비 수요 사이클과 인수·합병 통합 리스크, 환율 영향을 봐야 합니다.",
  },
  {
    rank: 98,
    name: "Verizon",
    ticker: "VZ",
    marketCap: "$200.34 B",
    marketCapBillion: 200.34,
    country: "미국",
    region: "북미",
    sector: "통신",
    sectorGroup: "통신·미디어",
    driver: "美 최대 이동통신사, 5G·FWA 가입자 확대",
    watch: "5G 투자 부담 속 배당 안정성과 무선 경쟁 구도 주목",
  },
  {
    rank: 99,
    name: "Commonwealth Bank",
    ticker: "CBA.AX",
    marketCap: "$199.56 B",
    marketCapBillion: 199.56,
    country: "호주",
    region: "오세아니아",
    sector: "은행",
    sectorGroup: "금융",
    driver: "호주 최대은행으로 예금 리더십과 주택담보대출 포트폴리오가 강점입니다.",
    watch: "호주 주택시장 둔화와 금리 변동, 신용손실 사이클을 봐야 합니다.",
  },
  {
    rank: 100,
    name: "Marvell Technology",
    ticker: "MRVL",
    marketCap: "$199.41 B",
    marketCapBillion: 199.41,
    country: "미국",
    region: "북미",
    sector: "데이터센터 네트워크",
    sectorGroup: "AI·반도체",
    driver: "AI 데이터센터용 커스텀 ASIC과 이더넷 스위치 칩으로 하이퍼스케일러 수요를 흡수하며 성장합니다.",
    watch: "AI 투자 사이클 둔화 시 고객 집중 리스크와 브로드컴과의 ASIC 경쟁을 봐야 합니다.",
  }
];












export const marketCapSectorGroups = Array.from(
  new Set(marketCapCompanies.map((company) => company.sectorGroup)),
);

export const marketCapRegions = Array.from(
  new Set(marketCapCompanies.map((company) => company.region)),
);
